POST http://localhost:3000/search-blogs
content-type: application/json
# authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTcwMDAxNzE2MTA1OTQwNmE5NDAzNCIsImlhdCI6MTcwNDM5NDc1M30.okINfZKLW_v0G1pBSTRvlbbf7thorcx9_CE25uySiQ0

{
    "tag": "tag1"
}